volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: /home/gsilva/data/wordpress
      o: bind
      type: none
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: /home/gsilva/data/mariadb
      o: bind
      type: none

networks:
  inception:
    driver: bridge

services:
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      - inception
    restart: on-failure
    ports:
      - '3306:3306'
    volumes:
      - mariadb:/var/lib/mysql
  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    depends_on:
      - wordpress
    networks:
      - inception
    restart: on-failure
    ports:
      - '443:443'
    volumes:
      - wordpress:/var/www/html
  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    networks:
      - inception
    depends_on:
      - mariadb
    ports:
      - '9000:9000'
    restart: on-failure
    env_file:
      - .env