volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: /home/gsilva/data/wordpress
      o: bind
      type: none

  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: /home/gsilva/data/mariadb
      o: bind
      type: none

networks:
  inception:
    driver: bridge

services:
  mariadb:
    container_name: mariadb
    build:
      context: ./srcs/requirements/mariadb
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      - inception
    ports:
      - '3306:3306'
    volumes:
      - mariadb:/var/lib/mysql
    restart: on-failure

  wordpress:
    container_name: wordpress
    build:
      context: ./srcs/requirements/wordpress
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      - inception
    depends_on:
      - mariadb
    ports:
      - '9000:9000'
    volumes:
      - wordpress:/var/www/html
    restart: on-failure

  nginx:
    container_name: nginx
    build:
      context: ./srcs/requirements/nginx
      dockerfile: Dockerfile
    networks:
      - inception
    depends_on:
      - wordpress
    ports:
      - '443:443'
    volumes:
      - wordpress:/var/www/html
    restart: on-failure